from django.urls import path
from . import views

urlpatterns = [
    path("api/support/notifications/", views.receive_trs_notification, name="receive_trs_notification",),
    path("api/support/notifications/<int:notification_id>/read/", views.mark_notification_read, name="mark_notification_read",),
    path("notifications/", views.notification_page, name="notification_page",),


    path('users/', views.user_list, name='user_list'),
    path('admin/users/toggle-status/<int:user_id>/', views.toggle_user_status, name='toggle_user_status'),
    path('', views.admin_login, name='admin_login'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-logout/', views.admin_logout, name='admin_logout'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/edit/<int:category_id>/', views.edit_category, name='edit_category'),
    path('catrgories/toggle/<int:category_id>/',views.toggle_category_status,name='toggle_category_status'),
    path('admin/categories/delete/<int:category_id>/', views.soft_delete_category, name='soft_delete_category'),
    path('categories/add/', views.add_category, name='add_category'),
    path('products/', views.product_list, name='product_list'),
    path('products/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('products/toggle/<int:product_id>/', views.toggle_product_status, name='toggle_product_status'), 
    path('products/delete/<int:product_id>',views.soft_product_delete,name='soft_product_delete'),
    path('products/add/', views.add_product, name='add_product'),
    path('brands/', views.brand_list, name='brand_list'),     
    path('brands/add/', views.add_brand, name='add_brand'),
    path('brands/edit/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('brands/toggle/<int:brand_id>/', views.toggle_brand_status, name='toggle_brand_status'), 
    path('brands/soft-delete/<int:brand_id>',views.soft_brand_delete,name='soft_brand_delete'),
    path('orders/', views.admin_order_list, name='admin_order_list'),
    path('orders/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('orders/update-status/<int:order_id>/', views.admin_update_order_status, name='admin_update_order_status'),
    path('orders/return/approve/<int:order_item_id>/', views.approve_return, name='admin_approve_return'),
    path('myadmin/orders/reject-return/<int:order_item_id>/', views.reject_return, name='admin_reject_return'),
    path('offers/',views.list_offers,name='list_offers'),
    path('offers/add-product/',views.add_product_offer,name='add_product_offer'),
    path('offers/add-category/',views.add_category_offer,name='add_category_offer'),
    path('offers/edit-product/<int:offer_id>/', views.edit_product_offer, name='edit_product_offer'),
    path('offers/edit-category/<int:offer_id>/', views.edit_category_offer, name='edit_category_offer'),
    path('offers/delete-product-offer/<int:offer_id>/', views.soft_product_offer_delete, name='soft_product_offer_delete'),
    path('offers/toggle-product-offer/<int:offer_id>/', views.toggle_product_offer_status, name='toggle_product_offer_status'),
    path('offers/toggle-category-offer/<int:offer_id>/', views.toggle_category_offer_status, name='toggle_category_offer_status'),
    path('offers/delete-category-offer/<int:offer_id>/', views.soft_category_offer_delete, name='soft_category_offer_delete'),
    path('coupon/',views.admin_coupon_list,name='admin_coupon_list'),
    path('coupon/add-coupon/',views.add_coupon,name='add_coupon'),
    path('coupon/edit-coupon/<int:coupon_id>',views.edit_coupon,name='edit_coupon'),
    path('coupon/delete-coupon/<int:coupon_id>',views.toggle_coupon,name='toggle_coupon'),
    path('coupons/delete/<int:coupon_id>/', views.soft_delete_coupon, name='soft_delete_coupon'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('admin/download_sales_report_csv/', views.download_sales_report_csv, name='download_sales_report_csv'),
    path('wallet/transactions/', views.wallet_transaction_list, name='wallet_transaction_list'),
    path('wallet/transactions/<str:transaction_id>/', views.wallet_transaction_detail, name='wallet_transaction_detail'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('myadmin/return-requests/', views.return_requests_dashboard, name='return_requests_dashboard'),


]

